# AM120 HW02
## Zachary Miller

In [1]:
import numpy as np
import scipy as scipy
from scipy import linalg
np.random.seed(123)

### 1a

In [15]:
# Initialize the matrices
A = np.array([[7.1188,0.96091,-8.2268],[0.96091,3.1457,-0.4717],[-8.2268,-0.4717,-7.2645]])
A_inv = np.linalg.inv(A)
U = scipy.linalg.orth(np.random.rand(3,2));

In [16]:
def iterate_bpm(A, U):
    U_1=A@U;
    U_1, _ = np.linalg.qr(U_1)
    
    return U_1

In [17]:
# Perform ten iterations of the block power method
U_list = []
for i in range(10):
    U = iterate_bpm(A_inv, U)
    U_list.append(U)
    print("Iteration", i+1, "U:")
    print(U)
    print()

eigval_1 = (A_inv@U[:,0]/(U[:,0]))[0]
eigval_2 = (A_inv@U[:,1]/(U[:,1]))[0]
    
print("Final eigenvectors (columns of U):")
print(U)
print()
print("Eigenvalue cooresponding to first eigenvector:", 1/eigval_1)
print("Eigenvalue cooresponding to second eigenvector:", 1/eigval_2)

Iteration 1 U:
[[-0.04745763 -0.54057698]
 [ 0.98584733 -0.16070814]
 [-0.16078811 -0.82580229]]

Iteration 2 U:
[[-0.06532186 -0.27842031]
 [ 0.99485723  0.05632287]
 [ 0.07740889 -0.95880648]]

Iteration 3 U:
[[-0.11824242 -0.54070422]
 [ 0.99227838 -0.03270892]
 [ 0.03744789 -0.84057663]]

Iteration 4 U:
[[-0.11950328 -0.27602096]
 [ 0.99128133  0.02052564]
 [ 0.05550036 -0.96093243]]

Iteration 5 U:
[[-0.12343239 -0.5418312 ]
 [ 0.99096234 -0.02296328]
 [ 0.05251745 -0.84017358]]

Iteration 6 U:
[[-0.12352506 -0.27570022]
 [ 0.99087874  0.01787065]
 [ 0.05385989 -0.96107754]]

Iteration 7 U:
[[-0.12381723 -0.54192152]
 [ 0.99085431 -0.02223949]
 [ 0.05363797 -0.84013479]]

Iteration 8 U:
[[-0.12382411 -0.27567521]
 [ 0.99084804  0.0176733 ]
 [ 0.05373782 -0.96108836]]

Iteration 9 U:
[[-0.12384585 -0.5419286 ]
 [ 0.99084622 -0.02218571]
 [ 0.05372132 -0.84013165]]

Iteration 10 U:
[[-0.12384636 -0.27567297]
 [ 0.99084575  0.01765868]
 [ 0.05372875 -0.96108927]]

Final eigenvectors 

__does not converge for the second eigenvalue because it is not unique. Can tell because the second column flips back and forth__

### 1b

In [18]:
x = np.random.rand(3,1)

In [19]:
def iterate_pm(A, x):
    x = A@x
    x = x/np.linalg.norm(x)
    
    return x

In [20]:
x_list = []
for i in range(10):
    x = iterate_pm(A_inv, x)
    x_list.append(x)
    print("Iteration", i+1, "x:")
    print(x)
    print()

eigval_1 = (A_inv@x/x)[0]
    
print("Final eigenvector:")
print(x)
print()
print("Cooresponding eigenvalue:", 1/eigval_1)


Iteration 1 x:
[[ 0.37536402]
 [ 0.51667522]
 [-0.7695119 ]]

Iteration 2 x:
[[0.38082175]
 [0.91121134]
 [0.15706267]]

Iteration 3 x:
[[-0.04819975]
 [ 0.99528485]
 [-0.08417157]]

Iteration 4 x:
[[-0.08177998]
 [ 0.99464509]
 [ 0.06319157]]

Iteration 5 x:
[[-0.11825796]
 [ 0.99203449]
 [ 0.04338932]]

Iteration 6 x:
[[-0.12072412]
 [ 0.99119241]
 [ 0.05443605]]

Iteration 7 x:
[[-0.1234329 ]
 [ 0.99093877]
 [ 0.05295921]]

Iteration 8 x:
[[-0.12361582]
 [ 0.99087172]
 [ 0.0537807 ]]

Iteration 9 x:
[[-0.12381726]
 [ 0.99085253]
 [ 0.05367083]]

Iteration 10 x:
[[-0.12383087]
 [ 0.99084751]
 [ 0.05373193]]

Final eigenvector:
[[-0.12383087]
 [ 0.99084751]
 [ 0.05373193]]

Cooresponding eigenvalue: [2.99965296]


### 1c

In [21]:
D1,V1=np.linalg.eig(A)

In [ ]:
# Show convergence of inverse block power method
for U in U_list:
    diff = U-V1

### 2

In [49]:
Q = np.matrix([
    [0, 0.5, 0, 0, 0, 0.5, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1/3, 1/3, 0, 0, 1/3],
    [0, 0, 0.5, 0.5, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0]])
print(Q)

[[0.         0.5        0.         0.         0.         0.5
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.        ]
 [0.         0.         1.         0.         0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.33333333 0.33333333 0.
  0.         0.33333333]
 [0.         0.         0.5        0.5        0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.        ]]


Since none of the rows are all 0, we will not run into the problem of being stuck at a node, and thus the adjustment $\hat{Q} = Q + \frac{1}{n}\vec{e}\vec{d}^{T}$ does nothing since $\vec{e}$ is all zeros. However, we do still have to adjust for the issue of being stuck at a subgraph, which we will do by creating $\hat{Q} = \alpha Q + (1-\alpha)\frac{1}{n}\vec{d}\vec{d}^{T}$.

In [50]:
alpha = 0.85
d = np.ones((8,1))
n = 8

Q_hat = alpha*Q + (1-alpha)*(1/n)*d*d.T
print(Q_hat)

[[0.01875    0.44375    0.01875    0.01875    0.01875    0.44375
  0.01875    0.01875   ]
 [0.01875    0.01875    0.01875    0.01875    0.01875    0.01875
  0.01875    0.86875   ]
 [0.01875    0.01875    0.01875    0.01875    0.01875    0.01875
  0.01875    0.86875   ]
 [0.01875    0.01875    0.86875    0.01875    0.01875    0.01875
  0.01875    0.01875   ]
 [0.86875    0.01875    0.01875    0.01875    0.01875    0.01875
  0.01875    0.01875   ]
 [0.01875    0.01875    0.01875    0.30208333 0.30208333 0.01875
  0.01875    0.30208333]
 [0.01875    0.01875    0.44375    0.44375    0.01875    0.01875
  0.01875    0.01875   ]
 [0.86875    0.01875    0.01875    0.01875    0.01875    0.01875
  0.01875    0.01875   ]]


Now we want to find the page rank $\vec{r}$ by solving $\vec{r} = Q^{T}\vec{r}$, which means finding the eigenvector cooresponding to the eigenvalue 1. Since $Q^{T}$ is a stochastic matrix, the Perron-Frobenius theorem garuntees that the largest eigenvalue of this matrix will be 1. Therefore, we can use the power method to find the cooresponding eigenvector. Doing that below...

In [67]:
x = np.random.rand(8,1)
x_list = []
for i in range(100):
    x = iterate_pm(Q_hat.T, x)
    x_list.append(x)
    
    if len(x_list) >= 2:
        diff = np.linalg.norm(x_list[i]-x_list[i-1])
        
        if diff < 0.001:
            print("Ran for", i, "total iterations")
            break;
            
        elif i == 99:
            print("Failed to converge")
            
        else: continue

print("\nFinal page rank:")
print(x)
            

Ran for 29 total iterations

Final page rank:
[[0.63637627]
 [0.3142743 ]
 [0.19188722]
 [0.15196544]
 [0.13323978]
 [0.3142743 ]
 [0.04406037]
 [0.56380868]]


In [71]:
A = np.matrix([
    [0,0,0,1,1,1,0],
    [0,0,1,0,0,1,1],
    [0,1,0,0,0,1,1],
    [1,0,0,0,1,0,1],
    [1,0,0,1,0,0,0],
    [1,1,1,0,0,0,0],
    [0,1,1,1,0,0,0]])
D = np.sum(A, axis=1)
D = np.diagflat(D)
L = D-A
print("Adjacency Matrix:")
print(A)
print("\nDegree Matrix:")
print(D)
print("\nLaplacian Matrix:")
print(L)

Adjacency Matrix:
[[0 0 0 1 1 1 0]
 [0 0 1 0 0 1 1]
 [0 1 0 0 0 1 1]
 [1 0 0 0 1 0 1]
 [1 0 0 1 0 0 0]
 [1 1 1 0 0 0 0]
 [0 1 1 1 0 0 0]]

Degree Matrix:
[[3 0 0 0 0 0 0]
 [0 3 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 3 0]
 [0 0 0 0 0 0 3]]

Laplacian Matrix:
[[ 3  0  0 -1 -1 -1  0]
 [ 0  3 -1  0  0 -1 -1]
 [ 0 -1  3  0  0 -1 -1]
 [-1  0  0  3 -1  0 -1]
 [-1  0  0 -1  2  0  0]
 [-1 -1 -1  0  0  3  0]
 [ 0 -1 -1 -1  0  0  3]]


(7, 7)