# AM120 HW08
## Zachary Miller

In [1]:
import numpy as np

### 1a i) and ii)
We are asked to create a random 140,000 standard normally distributed 2d vectors, and then to calculate their mean, variance, and covariance. We do this using the following equations
$$\bar{\vec{x}}= \frac{\sum_{i}^{n} x_i}{n}$$
$$Var(\vec{x}) = \frac{\sum_{i}^{n} (x_i-\bar{\vec{x}})^2}{n}$$
$$Cov(X) = XX^T/N$$
Doing this below...

In [26]:
np.random.seed(6968761)
N=140000
X=np.random.normal(size=(2,N))

# Function to calculate the row means
def calc_mean(arr):
    vec_sum = np.sum(arr, axis=1)
    return vec_sum/arr.shape[1]

# Function to calculate the row variances
def calc_variance(arr):
    mean_arr = calc_mean(arr)
    var_numer = np.sum(np.square(X-mean_arr.reshape(X.shape[0],-1)),
                      axis=1)
    var_denom = arr.shape[1]
    return var_numer/var_denom

# Function to calculate the covariance for a subset of the data points
def calc_covariance(arr, subset):
    arr_subset = arr[:,:subset]
    return np.matmul(arr_subset, arr_subset.T)/subset

comp_means = calc_mean(X)
comp_vars = calc_variance(X)
subsets = [14, 140, 1400, 14000, 140000]
    
print(f'Component Means: {comp_means}')
print(f'Component Variances: {comp_vars}')

for subset in subsets:
    cov_mat = calc_covariance(X, subset)
    print(f'Covariance Matrix for {subset} Data points:\n{cov_mat}')

Component Means: [-0.00255699 -0.00362471]
Component Variances: [1.00199433 1.0047822 ]
Covariance Matrix for 14 Data points:
[[ 1.04076445 -0.01401101]
 [-0.01401101  0.87987283]]
Covariance Matrix for 140 Data points:
[[ 0.84186369 -0.10970489]
 [-0.10970489  1.25297686]]
Covariance Matrix for 1400 Data points:
[[0.98446752 0.03978158]
 [0.03978158 0.98221125]]
Covariance Matrix for 14000 Data points:
[[ 1.00984748 -0.00111566]
 [-0.00111566  1.0014379 ]]
Covariance Matrix for 140000 Data points:
[[ 1.00200087 -0.00379688]
 [-0.00379688  1.00479534]]


The above component means and variances are very close to 0 and 1. This is to be expected since we drew each coordinate for each point from a standard normal distribution. The progression of the covariance matrices as we include more points also makes sense. Because all of the elements of both components were drawn independently, we would expect the covaraince matrix to be 1 along the diagonal (since each component has varaince 1) and zero everywhere else (since the variables are independent and therefore should have no covariance). For small N, we have more noise in the matrix, but as we increase N that noise gets smaller and we begin to converge towards the expected result. 