# AM120 HW05
## Zachary Miller
### 1a

In [35]:
import numpy as np
import scipy.linalg

In [40]:
A = np.array([[4,0,4],
              [0,-3,-4],
              [8,-3,4],
              [20,-6,12]])
b = np.array([-4,1,-3,0]).T

We are asked to solve the above system using least-squares, which means we want to solve $A^TA\vec{x}=A^T\vec{b}$. However, as we can see below, $A^TA$ is has a detirminant of approximately zero and is of rank 2 so there are infinite solutions for $\vec{x}$.

In [41]:
A_tA = A.T@A
print("A_tA: \n", A_tA)
print("Detirminant of A_tA: \n", np.linalg.det(A_tA))
print("Rank of A_tA: \n", np.linalg.matrix_rank(A_tA))

A_tA: 
 [[ 480 -144  288]
 [-144   54  -72]
 [ 288  -72  192]]
Detirminant of A_tA: 
 1.9645085558295291e-10
Rank of A_tA: 
 2


In order to find a unique solution, we have to add an additional constraint to our original least-squares formulation. We now require that the solution $\vec{x}$ minimizes both the error and the norm of the solution. This can be found using the pseudo inverse to get $\vec{x}=(A^TA)^{\dagger}A^T\vec{b}$ which can be simplifed to $\vec{x}=A^{\dagger}\vec{b}$. Solving below...

In [54]:
# Get the SVD of A
U, Sigma, V_t = np.linalg.svd(A, full_matrices=True)

# Make the Sigma array from the list of singular values
Sigma_diag = np.diag(Sigma)
Sigma_mat = np.zeros(A.shape)
Sigma_mat[:Sigma_diag.shape[0],:Sigma_diag.shape[1]] = Sigma_diag

# Calculate the pseudo inverse of Sigma_mat
Sigma_mat_pinv = np.copy(Sigma_mat)
Sigma_mat_pinv[Sigma_mat_pinv<1e-14]=0
Sigma_mat_pinv[Sigma_mat_pinv != 0] = 1/Sigma_mat_pinv[Sigma_mat_pinv != 0]
Sigma_mat_pinv = Sigma_mat_pinv.T

# Calculate the pseudo inverse of A using the formula above
A_pinv = V_t.T@Sigma_mat_pinv@U.T
my_x = A_pinv@b
py_x = np.linalg.lstsq(A,b,rcond=None)[0]

print("Pseudo Inverse of Sigma:\n", Sigma_mat_pinv)
print("\nPseudo Inverse of A:\n", A_pinv)
print("\nMy Solution:\n", my_x)
print("\nSolution using np.linalg.lstsq:\n", py_x)


Pseudo Inverse of Sigma:
 [[0.03785218 0.         0.         0.        ]
 [0.         0.18878107 0.         0.        ]
 [0.         0.         0.         0.        ]]

Pseudo Inverse of A:
 [[-0.00857843  0.03676471  0.01960784  0.03063725]
 [ 0.04411765 -0.11764706 -0.02941176 -0.01470588]
 [ 0.0502451  -0.12009804 -0.01960784  0.01102941]]

My Solution:
 [ 0.0122549  -0.20588235 -0.2622549 ]

Solution using np.linalg.lstsq:
 [ 0.0122549  -0.20588235 -0.2622549 ]


Comparing our answer to the one obtained using np.linalg.lstsq, we can see that they are the same. From this, we can infer that when faced with infinite possible solutions, np.linalg.lstsq returns the one with the smallest norm.

### 1b

In [58]:
A = np.array([[-3,-3,2],[-9,-9,6]])
b = np.array([2,4]).T

print("A:\n", A)

A:
 [[-3 -3  2]
 [-9 -9  6]]


Just by looking at the printout of $A$ above, we can see that the second column is the same as the first, and the third column is $-2/3$ times the first column. Therefore, we can immediatly tell that the columns are all linearly dependent, and the rank of $A$ is 1. This implies that there are two free variables, and thus infinite solutions. Again, in order to find a unique solution for this system of equations, we will use the pseudo inverse of $A$ (which we will again find via SVD) to find $\vec{x}=A^{\dagger}\vec{b}$. Doing so below...

In [59]:
# Get the SVD of A
U, Sigma, V_t = np.linalg.svd(A, full_matrices=True)

# Make the Sigma array from the list of singular values
Sigma_diag = np.diag(Sigma)
Sigma_mat = np.zeros(A.shape)
Sigma_mat[:Sigma_diag.shape[0],:Sigma_diag.shape[1]] = Sigma_diag

# Calculate the pseudo inverse of Sigma_mat
Sigma_mat_pinv = np.copy(Sigma_mat)
Sigma_mat_pinv[Sigma_mat_pinv<1e-14]=0
Sigma_mat_pinv[Sigma_mat_pinv != 0] = 1/Sigma_mat_pinv[Sigma_mat_pinv != 0]
Sigma_mat_pinv = Sigma_mat_pinv.T

# Calculate the pseudo inverse of A using the formula above
A_pinv = V_t.T@Sigma_mat_pinv@U.T
my_x = A_pinv@b
py_x = np.linalg.lstsq(A,b,rcond=None)[0]

print("Pseudo Inverse of Sigma:\n", Sigma_mat_pinv)
print("\nPseudo Inverse of A:\n", A_pinv)
print("\nMy Solution:\n", my_x)
print("\nSolution using np.linalg.lstsq:\n", py_x)


Pseudo Inverse of Sigma:
 [[0.06741999 0.        ]
 [0.         0.        ]
 [0.         0.        ]]

Pseudo Inverse of A:
 [[-0.01363636 -0.04090909]
 [-0.01363636 -0.04090909]
 [ 0.00909091  0.02727273]]

My Solution:
 [-0.19090909 -0.19090909  0.12727273]

Solution using np.linalg.lstsq:
 [-0.19090909 -0.19090909  0.12727273]


### 2a

In [61]:
import numpy as np
import scipy.linalg

In [60]:
A = np.array([[ 6, 8, 6],
              [-2, 4, 10],
              [0, -3, 2],
              [4, 3, 2],
              [6, -0, 7]])
b = np.array([5,-4,-8,2,-2]).T

The solution to the above overdetirmined system $A\vec{x}=\vec{b}$ is the $\vec{x}$ that minimizes the norm of the error $\vec{e}=||A\vec{x}-\vec{b}||^2$, which is given by $\vec{e}^T\vec{e}$. To do this, we take the derivative with respect to $\vec{x}$ of $\vec{e}^T\vec{e}$ and set it to zero. After some calculus, this comes out to be 

$$2(A^TA\vec{x}-A^T\vec{b})=0$$ $$A^TA\vec{x}=A^T\vec{b}$$ $$\vec{x}=(A^TA)^{-1}A^T\vec{b}$$ 

Calculating below...

In [64]:
x_sol = np.linalg.inv(A.T@A)@A.T@b
print("Least squares solution:\n", x_sol)

Least squares solution:
 [ 0.32153484  1.09494635 -0.79573356]


### 2b


### 3a

In [67]:
import numpy as np
import scipy.linalg

Recall that the proccess we learned prvioiusly for doing PCA was to first calculate the normalized covariance matrix $C = FF^T/N$, and then the principal components of F were the eigenvectors of C. When doing PCA via SVD, we first calculate $F = U\Sigma V^T$. Recall that to calculate U, we calculate the normalized eigenvectors of $FF^T$, which is the same as the eigenvectors of $C$. Therefore, we can see that the columns of U from SVD are the same as the PCs of F. 

When the covariance matrix was used to calculate the PCs, we obtaine the time series $T$ by calculating $T=U^TF$. If we plug in the SVD composition of F for F, we get
$$T = U^T(U\Sigma V^T)$$
$$T = \Sigma V^T$$

Finally, since the singluar values along the diagonal of $\Sigma$ are the square roots of the eigenvalues cooresponding to the eigenvectors that make up the columns of $U$, we can also get back varaince explained for each PC. 

Therefore, we can see that from the SVD of a data matrix $F$ ,we can get the PCs, their explained variance, and the PC time series. We can also see that the method of doing PCA using SVD will be the same as if we did it using the covariance matrix. 

### 3b

In [79]:
F = np.array([[0,-18,2.5,-10,5,-2.5,7.5,5,10],
             [10,25,2.5,12,-5,0,-12,-12,-20],
             [-30,12,-20,12,-10,12,0,12,10]])

We are asked to calculat the PCs and expansion foefficients using both SVD and the corvariance matrix methods. First let's do this via SVD using the method described in part A

In [92]:
### First do PCA using SVD ###

# Get the SVD of A
U_svd, Sigma, V_t = np.linalg.svd(F, full_matrices=True)

# Get list of singular values into matrix form
Sigma_diag = np.diag(Sigma)
Sigma_mat = np.zeros(F.shape)
Sigma_mat[:Sigma_diag.shape[0],:Sigma_diag.shape[1]] = Sigma_diag

# Calculat the expansion coefficients
T_svd = Sigma_mat@V_t

### Now do PCA using covariance matrix ###

# Calculate the covariance matrix
C = F@F.T/F.shape[1]

# Calculate the eigenvectors and eigenvalues of F
eigvals, eigvecs = np.linalg.eig(C)

# Sort the eigenvectors so that the eigenvectors cooresponding to the largest eigenvalues
# are first
inds = (-np.abs(eigvals)).argsort()
U_cov = eigvecs [:,inds]
eigvals = eigvals[inds]

# Calculate the expansion coefficients
T_cov = U_cov.T@F

### Compare Results ###
print("PCs (columns) using SVD:\n", U_svd)
print("PCs (columns) using Covariance Matrix:\n", U_cov)
print("\nExpansion Coefficients using SVD:\n", T_svd)
print("Expansion Coefficients using Covariance Matrix:\n", T_cov)

PCs (columns) using SVD:
 [[-0.45308868 -0.30380604  0.83810055]
 [ 0.83700581  0.17858356  0.51723224]
 [-0.30680926  0.9358471   0.17337323]]
PCs (columns) using Covariance Matrix:
 [[-0.45308868 -0.30380604 -0.83810055]
 [ 0.83700581  0.17858356 -0.51723224]
 [-0.30680926  0.9358471  -0.17337323]]

Expansion Coefficients using SVD:
 [[ 1.75743358e+01  2.53990304e+01  7.09597798e+00  1.08932454e+01
  -3.38237988e+00 -2.54898939e+00 -1.34422348e+01 -1.59912242e+01
  -2.43390956e+01]
 [-2.62895775e+01  2.11632630e+01 -1.90299983e+01  1.64112284e+01
  -1.17704190e+01  1.19896803e+01 -4.42154802e+00  7.56813232e+00
   2.74873943e+00]
 [-2.88746561e-02 -7.45252743e-02 -7.91327010e-02 -9.37399063e-02
  -1.29390746e-01 -1.47725798e-02  7.89673266e-02  6.41947468e-02
  -2.29906836e-01]]
Expansion Coefficients using Covariance Matrix:
 [[ 1.75743358e+01  2.53990304e+01  7.09597798e+00  1.08932454e+01
  -3.38237988e+00 -2.54898939e+00 -1.34422348e+01 -1.59912242e+01
  -2.43390956e+01]
 [-2.628

Looking at the results above, we can see that the numbers are all the same, save for some differences in sign. As we have seen in previous problems, since eigenvectors are only uniquely detirmined up to a minus sign, principal components may come out with different signs depending on how they are calculated. Importantly, however, the interpretation of each principal component remains the same. 

In [89]:
U_cov

array([[-0.45308868, -0.30380604, -0.83810055],
       [ 0.83700581,  0.17858356, -0.51723224],
       [-0.30680926,  0.9358471 , -0.17337323]])

In [90]:
U_svd

array([[-0.45308868, -0.30380604,  0.83810055],
       [ 0.83700581,  0.17858356,  0.51723224],
       [-0.30680926,  0.9358471 ,  0.17337323]])